import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import CommentCard from "../components/CommentCard";
import Link from "next/link";

export default function Home() {
  console.log(props.comments);
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to My <a href="https://nextjs.org">Next.js! App</a>
        </h1>
        <section>
          <div className="flex flex-wrap gap-8">
            {props.comments?.map((data) => (
              <div key={data.id}>
                <CommentCard
                  postID={data.postID}
                  id={data.id}
                  name={data.name}
                  email={data.email}
                  comment={data.body}
                />
              </div>
            ))}
          </div>
        </section>
        <p className={styles.description}>Click below to see more comments</p>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  const response = await fetch('https://jsonplaceholder.typicode.com/post/1/comments')
  const comments = await response.json();
  return { 
      props: { comments } 
  }
}